### ISSUE TITLE
save checkpoints

### ISSUE THREAD

**Issue by pretbc** [2U1/Phi3-Vision-Finetune#18]
Hello there,

I was nable to start Qlora training but I cannot save checkpoint. It seems that classes mentioned in error below should be saved using 'save_pretrained'  ?

```
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/peft/peft_model.py", line 737, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'PeftModelForCausalLM' object has no attribute 'save_checkpoint'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 356, in __getattr__
    return super().__getattr__(name)  # defer to nn.Module's logic
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LoraModel' object has no attribute 'save_checkpoint'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/pycharm_project_444/src/training/train.py", line 222, in <module>
    train()
  File "/tmp/pycharm_project_444/src/training/train.py", line 197, in train
    trainer.train()
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/trainer.py", line 1948, in train
    return inner_training_loop(
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2366, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, grad_norm, model, trial, epoch, ignore_keys_for_eval)
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2817, in _maybe_log_save_evaluate
    self._save_checkpoint(model, trial, metrics=metrics)
  File "/tmp/pycharm_project_444/src/training/trainer.py", line 137, in _save_checkpoint
    super(Phi3VTrainer, self)._save_checkpoint(model, trial, metrics)
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/trainer.py", line 2900, in _save_checkpoint
    self._save_optimizer_and_scheduler(output_dir)
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/trainer.py", line 3000, in _save_optimizer_and_scheduler
    inspect.signature(self.model_wrapped.save_checkpoint).parameters.keys()
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/peft/peft_model.py", line 741, in __getattr__
    return getattr(self.base_model, name)
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/peft/tuners/lora/model.py", line 360, in __getattr__
    return getattr(self.model, name)
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Phi3VForCausalLM' object has no attribute 'save_checkpoint'
```

**Comment by 2U1** [comment]
https://github.com/2U1/Phi3-Vision-Finetune/issues/17#issuecomment-2298326760

It looks like the issue is caused by using 1 gpu for deepspeed. You could run using torchrun or just erase the deepspeed config and run the python script.

**Comment by pretbc** [comment]
Im using pycharm config , and starting it like in last comment from #17

![image](https://github.com/user-attachments/assets/2cb46fb3-76ad-4a5c-a18b-3584eac0b1ce)

**Comment by pretbc** [comment]
going to close this issue as duplicate #17 , going to continue in 17
