### ISSUE TITLE
Merge Lora params 

### ISSUE THREAD

**Issue by pretbc** [2U1/Phi3-Vision-Finetune#19]
Hello after training Qlora I got produce checkpoint under

```
ll output/lora_vision_test/

adapter_config.json
adapter_model.safetensors
checkpoint-178/
config.json
non_lora_state_dict.bin
README.md
trainer_state.json
```

Is this correct approach to run merg lora sh ?

```
python src/merge_lora_weights.py \
    --model-path output/lora_vision_test \                                   
    --model-base microsoft/Phi-3-vision-128k-instruct  \       
    --save-model-path output/merged_dir
    --safe-serialization
```

and then

```
python -m src.serve.cli \
 --model-path output/merged_dir
 --image-file cherry/some.png

```

thx

**Comment by pretbc** [comment]
also I see an issue when trying to merge

```
python src/merge_lora_weights.py --model-path output/lora_vision_test --model-base Phi-3-vision-128k-instruct --save-model-path output/merged_output --safe-serialization 
```

```
/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/models/auto/image_processing_auto.py:513: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
Loading Phi3-Vision from base model...
Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Loading checkpoint shards:   0%|                                                                                                                                                                                                                                                       | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/tmp/pycharm_project_444/src/merge_lora_weights.py", line 31, in <module>
    merge_lora(args)
  File "/tmp/pycharm_project_444/src/merge_lora_weights.py", line 6, in merge_lora
    processor, model = load_pretrained_model(args.model_path, args.model_base, model_name, device_map='cpu')
  File "/tmp/pycharm_project_444/src/utils.py", line 44, in load_pretrained_model
    model = Phi3VForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs)
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3941, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4415, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/modeling_utils.py", line 938, in _load_state_dict_into_meta_model
    hf_quantizer.create_quantized_param(model, param, param_name, param_device, state_dict, unexpected_keys)
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 191, in create_quantized_param
    raise ValueError(
ValueError: Supplied state dict for model.layers.0.mlp.down_proj.weight does not contain `bitsandbytes__*` and possibly other `quantized_stats` components.

```

output ls

```
ls output/lora_vision_test/
adapter_config.json  adapter_model.safetensors  checkpoint-178  config.json  non_lora_state_dict.bin  README.md  trainer_state.json
```

```
ls output/lora_vision_test/checkpoint-178/
adapter_config.json        config.json     latest                            model-00002-of-00002.safetensors  preprocessor_config.json  rng_state.pth  special_tokens_map.json  tokenizer.json      training_args.bin
adapter_model.safetensors  global_step178  model-00001-of-00002.safetensors  model.safetensors.index.json      README.md                 scheduler.pt   tokenizer_config.json    trainer_state.json  zero_to_fp32.py
```

**Comment by 2U1** [comment]
@pretbc Sorry for your inconvinience. There is a bash script for merging lora. You could use it.
Also, I'll find the issue and solve it soon. 
Again, I'm sorry for the inconvinience.

**Comment by 2U1** [comment]
@pretbc It seems like for the QLoRa, You need to adjust the code for it. 
import argparse
from utils import get_model_name_from_path, load_pretrained_model

```
import argparse
from utils import get_model_name_from_path, load_pretrained_model

def merge_lora(args):
    model_name = get_model_name_from_path(args.model_path)
    processor, model = load_pretrained_model(model_path=args.model_path, model_base=args.model_base,
                                             model_name=model_name, device_map='cpu',
                                             load_8bit=args.load_8bit, load_4bit=args.load_4bit)

    if args.safe_serialization:
        from accelerate import Accelerator
        accel = Accelerator()
        # You could set the shard size whatever you want
        accel.save_model(model, args.save_model_path, max_shard_size = '5GB')
        model.config.save_pretrained(args.save_model_path)
        processor.save_pretrained(args.save_model_path)


    else:
        model.save_pretrained(args.save_model_path, safe_serialization=False)
        processor.save_pretrained(args.save_model_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-path", type=str, required=True)
    parser.add_argument("--model-base", type=str, required=True)
    parser.add_argument("--save-model-path", type=str, required=True)
    parser.add_argument("--safe-serialization", action='store_true')
    parser.add_argument("--load-8bit", action='store_true')
    parser.add_argument("--load-4bit", action='store_true')

    args = parser.parse_args()

    merge_lora(args)
```
    
This is the code for it. Can you add your quantized option for it?

**Comment by pretbc** [comment]
Hello there:

I pasted your code to the lmerge_lora_weights.py but that did not resolve issue

```
/tmp/pycharm_project_444$ python src/merge_lora_weights.py --model-path output/lora_vision_test --model-base Phi-3-vision-128k-instruct --save-model-path output/merged_output --safe-serialization --load-4bit 
```

```
/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/models/auto/image_processing_auto.py:513: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
Loading Phi3-Vision from base model...
Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/quantizers/auto.py:174: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used.
  warnings.warn(warning_msg)
Loading checkpoint shards:   0%|                                                                                                                                                                                                                                                       | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/tmp/pycharm_project_444/src/merge_lora_weights.py", line 67, in <module>
    merge_lora(args)
  File "/tmp/pycharm_project_444/src/merge_lora_weights.py", line 38, in merge_lora
    processor, model = load_pretrained_model(model_path=args.model_path, model_base=args.model_base,
  File "/tmp/pycharm_project_444/src/utils.py", line 44, in load_pretrained_model
    model = Phi3VForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, config=lora_cfg_pretrained, **kwargs)
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3941, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4415, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/modeling_utils.py", line 938, in _load_state_dict_into_meta_model
    hf_quantizer.create_quantized_param(model, param, param_name, param_device, state_dict, unexpected_keys)
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/quantizers/quantizer_bnb_4bit.py", line 191, in create_quantized_param
    raise ValueError(
ValueError: Supplied state dict for model.layers.0.mlp.down_proj.weight does not contain `bitsandbytes__*` and possibly other `quantized_stats` components.
```

**Comment by pretbc** [comment]
@2U1  any update ?

**Comment by 2U1** [comment]
@pretbc Not much. Instead using `zero3_offload ` without Quantization can used for training.
I will work around a bit more.

**Comment by 2U1** [comment]
@pretbc I was working around and you can extract the `quantization_config` from the config.json but, still can't merge it. 
However you can still use 'model.load_adpater' method to use your weights.

**Comment by 2U1** [comment]
@pretbc 
```
import argparse
from utils import get_model_name_from_path, load_pretrained_model
import torch
from transformers import AutoModelForCausalLM, AutoProcessor
from peft import PeftModel
from accelerate import Accelerator
import os

def merge_lora(args):
    model_name = get_model_name_from_path(args.model_path)
    # processor, model = load_pretrained_model(model_path=args.model_path, model_base=args.model_base,
    #                                          model_name=model_name, device_map='cpu',
    #                                          load_8bit=args.load_8bit, load_4bit=args.load_4bit)

    model = AutoModelForCausalLM.from_pretrained('microsoft/Phi-3.5-vision-instruct', low_cpu_mem_usage=True, trust_remote_code=True, torch_dtype=torch.float16)
    processor = AutoProcessor.from_pretrained('microsoft/Phi-3.5-vision-instruct', trust_remote_code=True)

    token_num, tokem_dim = model.lm_head.out_features, model.lm_head.in_features

    if model.lm_head.weight.shape[0] != token_num:
        model.lm_head.weight = torch.nn.Parameter(torch.empty(token_num, tokem_dim, device=model.device, dtype=model.dtype))
        model.model.embed_tokens.weight = torch.nn.Parameter(torch.empty(token_num, tokem_dim, device=model.device, dtype=model.dtype))

    print('Loading additional Phi3-Vision weights...')
    non_lora_trainables = torch.load(os.path.join(args.model_path, 'non_lora_state_dict.bin'), map_location='cpu')
    non_lora_trainables = {(k[11:] if k.startswith('base_model.') else k): v for k, v in non_lora_trainables.items()}
    if any(k.startswith('model.model.') for k in non_lora_trainables):
        non_lora_trainables = {(k[6:] if k.startswith('model.') else k): v for k, v in non_lora_trainables.items()}
    model.load_state_dict(non_lora_trainables, strict=False)

    print('Loading LoRA weights...')
    model = PeftModel.from_pretrained(model, args.model_path)

    print('Merging LoRA weights...')
    model = model.merge_and_unload()

    print('Model Loaded!!!')

    if args.safe_serialization:
        from accelerate import Accelerator
        accel = Accelerator()
        # You could set the shard size whatever you want
        accel.save_model(model, args.save_model_path, max_shard_size = '5GB')
        model.config.save_pretrained(args.save_model_path)
        processor.save_pretrained(args.save_model_path)


    else:
        model.save_pretrained(args.save_model_path, safe_serialization=False)
        processor.save_pretrained(args.save_model_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-path", type=str, required=True)
    parser.add_argument("--model-base", type=str, required=True)
    parser.add_argument("--save-model-path", type=str, required=True)
    parser.add_argument("--safe-serialization", action='store_true')

    args = parser.parse_args()

    merge_lora(args)
```
This will work fine for you. I just tested.

**Comment by pretbc** [comment]
hmm I pull master and did re-training with the same params. 

Adnd I end-up with some mismatch of sizes


```
You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.37it/s]
/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/transformers/models/auto/image_processing_auto.py:513: FutureWarning: The image_processor_class argument is deprecated and will be removed in v4.42. Please use `slow_image_processor_class`, or `fast_image_processor_class` instead
  warnings.warn(
Loading additional Phi3-Vision weights...
/tmp/pycharm_project_444/src/merge_lora_weights.py:58: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  non_lora_trainables = torch.load(os.path.join(args.model_path, 'non_lora_state_dict.bin'), map_location='cpu')
Traceback (most recent call last):
  File "/tmp/pycharm_project_444/src/merge_lora_weights.py", line 95, in <module>
    merge_lora(args)
  File "/tmp/pycharm_project_444/src/merge_lora_weights.py", line 62, in merge_lora
    model.load_state_dict(non_lora_trainables, strict=False)
  File "/home/pretbc/.virtualenvs/Phi3-Vision-Finetune/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Phi3VForCausalLM:
        size mismatch for lm_head.weight: copying a param with shape torch.Size([49250304, 1]) from checkpoint, the shape in current model is torch.Size([32064, 3072]).
```

same error for above code snippet , and current master `merge_lora` implementation

**Comment by 2U1** [comment]
@pretbc Oh, Sorry I haven't wrote that, when tuning `embed_tokens` with LoRA, You need to tune `lm_head` with it. 
You should fix your scripts like this.
`--lora_namespan_exclude "['lm_head', 'embed_tokens']" \`

**Comment by pretbc** [comment]
Great news - its working :) Gonna close issue as resolved
