### ISSUE TITLE
ValueError: The repository for /kaggle/working/Phi3-Vision-Finetune/output/lora_vision_test contains custom code which must be executed to correctly load the model.

### ISSUE THREAD

**Issue by abhijeetsourav** [2U1/Phi3-Vision-Finetune#22]
while merging the lora weights with the **merge_lora_weights.py**, I got this error

Here's the parameters for merge_lora_weights.py
`python src/merge_lora_weights.py \
    --model-path /kaggle/working/Phi3-Vision-Finetune/output/lora_vision_test \
    --model-base $MODEL_NAME  \
    --save-model-path /kaggle/working/Phi3-Vision-Finetune/output \
    --safe-serialization
`

### Full error
``
The repository for /kaggle/working/Phi3-Vision-Finetune/output/lora_vision_test contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//kaggle/working/Phi3-Vision-Finetune/output/lora_vision_test.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 612, in resolve_trust_remote_code
    answer = input(
  File "/opt/conda/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 593, in _raise_timeout_error
    raise ValueError(
ValueError: Loading this model requires you to execute custom code contained in the model repository on your local machine. Please set the option `trust_remote_code=True` to permit loading of this model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/kaggle/working/Phi3-Vision-Finetune/src/merge_lora_weights.py", line 31, in <module>
    merge_lora(args)
  File "/kaggle/working/Phi3-Vision-Finetune/src/merge_lora_weights.py", line 6, in merge_lora
    processor, model = load_pretrained_model(model_path=args.model_path, model_base=args.model_base,
  File "/kaggle/working/Phi3-Vision-Finetune/src/utils.py", line 41, in load_pretrained_model
    lora_cfg_pretrained = AutoConfig.from_pretrained(model_path)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 937, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/opt/conda/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 625, in resolve_trust_remote_code
    raise ValueError(
ValueError: The repository for /kaggle/working/Phi3-Vision-Finetune/output/lora_vision_test contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//kaggle/working/Phi3-Vision-Finetune/output/lora_vision_test.
Please pass the argument `trust_remote_code=True` to allow custom code to be run.
``

**Comment by 2U1** [comment]
I've added the `trust_remote_code` options so it will be fine now.
