### ISSUE TITLE
Why is 

### ISSUE THREAD

**Issue by eshwanthkartitr** [2U1/Phi3-Vision-Finetune#23]
(.venv) (base) root@d7f34e41228d:~/Phi3-Vision-Finetune# python -m src.serve.app --model-path "/home/Phi3-Vision-Finetune/output/model"
The repository for /home/Phi3-Vision-Finetune/output/model contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//home/Phi3-Vision-Finetune/output/model.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] Traceback (most recent call last):
  File "/home/.venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 612, in resolve_trust_remote_code
    answer = input(
  File "/home/.venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 593, in _raise_timeout_error
    raise ValueError(
ValueError: Loading this model requires you to execute custom code contained in the model repository on your local machine. Please set the option `trust_remote_code=True` to permit loading of this model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/Phi3-Vision-Finetune/src/serve/app.py", line 131, in <module>
    main(args)
  File "/home/Phi3-Vision-Finetune/src/serve/app.py", line 85, in main
    processor, model = load_pretrained_model(model_base = args.model_base, model_path = args.model_path,
  File "/home/Phi3-Vision-Finetune/src/utils.py", line 68, in load_pretrained_model
    processor = AutoProcessor.from_pretrained(model_path)
  File "/home/.venv/lib/python3.10/site-packages/transformers/models/auto/processing_auto.py", line 301, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/home/.venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 625, in resolve_trust_remote_code
    raise ValueError(
ValueError: The repository for /home/Phi3-Vision-Finetune/output/model contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co//home/Phi3-Vision-Finetune/output/model.
Please pass the argument `trust_remote_code=True` to allow custom code to be run.

**Comment by 2U1** [comment]
Sorry for the inconvinience, You could add `trust_remote_code=True` to the utils.py model and processor loading line.
