### ISSUE TITLE
ModuleNotFoundError: No module named 'transformers_modules.microsoft.Phi-3'

### ISSUE THREAD

**Issue by abhijeetsourav** [2U1/Phi3-Vision-Finetune#24]
while running inference after **merging lora weights** with the following script
`
!python -m src.serve.cli \
 --model-path /kaggle/working/Phi3-Vision-Finetune/output \
 --image-file /kaggle/working/dataset/train_images/71XKEn+9WSL.jpg
`

I ran into the error:
full error is as follows:
`
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/kaggle/working/Phi3-Vision-Finetune/src/serve/cli.py", line 141, in <module>
    main(args)
  File "/kaggle/working/Phi3-Vision-Finetune/src/serve/cli.py", line 64, in main
    processor, model = load_pretrained_model(model_path = args.model_path, model_base=args.model_base, 
  File "/kaggle/working/Phi3-Vision-Finetune/src/utils.py", line 68, in load_pretrained_model
    model = AutoModelForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, trust_remote_code=True, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 551, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "/opt/conda/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 514, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module)
  File "/opt/conda/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 212, in get_class_in_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.cache/huggingface/modules/transformers_modules/microsoft/Phi-3.5-vision-instruct/c69b58c1be8dfda05972fdf495be3511e3b0f61f/modeling_phi3_v.py", line 47, in <module>
    from .configuration_phi3_v import Phi3VConfig
ModuleNotFoundError: No module named 'transformers_modules.microsoft.Phi-3'
`

**Comment by 2U1** [comment]
Sorry for the inconviniecne. 
Open your config file in the output directory and change your config option like this.
`"AutoConfig": "configuration_phi3_v.Phi3VConfig",`

**Comment by 2U1** [comment]
The issue is caused by `trust_remote_code` when merging LoRA weights. So I've just made a code to manually fix the config file, and now it will work.
