### ISSUE TITLE
Recomputed values for the following tensors have different metadata than during the forward pass.

### ISSUE THREAD

**Issue by ephron-canopy** [2U1/Phi3-Vision-Finetune#32]
I am facing this error while trying to fine-tune the phi3.5 vision model with lora.

created the virtual env based on the environment.yaml file,
all the library version are as mentioned.

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/home/ubuntu/My_work/SSN_extraction/Phi3-Vision-Finetune/src/training/train.py", line 232, in <module>
[rank0]:     train()
[rank0]:   File "/home/ubuntu/My_work/SSN_extraction/Phi3-Vision-Finetune/src/training/train.py", line 207, in train
[rank0]:     trainer.train()
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/transformers/trainer.py", line 2122, in train
[rank0]:     return inner_training_loop(
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/transformers/trainer.py", line 2474, in _inner_training_loop
[rank0]:     tr_loss_step = self.training_step(model, inputs, num_items_in_batch)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/transformers/trainer.py", line 3606, in training_step
[rank0]:     self.accelerator.backward(loss, **kwargs)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/accelerate/accelerator.py", line 2188, in backward
[rank0]:     self.deepspeed_engine_wrapped.backward(loss, **kwargs)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/accelerate/utils/deepspeed.py", line 166, in backward
[rank0]:     self.engine.backward(loss, **kwargs)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1967, in backward
[rank0]:     self.optimizer.backward(loss, retain_graph=retain_graph)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/deepspeed/runtime/zero/stage3.py", line 2213, in backward
[rank0]:     self.loss_scaler.backward(loss.float(), retain_graph=retain_graph)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/deepspeed/runtime/fp16/loss_scaler.py", line 63, in backward
[rank0]:     scaled_loss.backward(retain_graph=retain_graph)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/torch/_tensor.py", line 581, in backward
[rank0]:     torch.autograd.backward(
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/torch/autograd/function.py", line 307, in apply
[rank0]:     return user_fn(self, *args)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 511, in decorate_bwd
[rank0]:     return bwd(*args, **kwargs)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/deepspeed/runtime/zero/linear.py", line 73, in backward
[rank0]:     input, weight, bias = ctx.saved_tensors
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 1129, in unpack_hook
[rank0]:     frame.check_recomputed_tensors_match(gid)
[rank0]:   File "/opt/conda/envs/phi3v_v2/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 903, in check_recomputed_tensors_match
[rank0]:     raise CheckpointError(
[rank0]: torch.utils.checkpoint.CheckpointError: torch.utils.checkpoint: Recomputed values for the following tensors have different metadata than during the forward pass.
[rank0]: tensor at position 4:
[rank0]: saved metadata: {'shape': torch.Size([3072]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: tensor at position 6:
[rank0]: saved metadata: {'shape': torch.Size([9216, 3072]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: tensor at position 23:
[rank0]: saved metadata: {'shape': torch.Size([3072, 3072]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: tensor at position 33:
[rank0]: saved metadata: {'shape': torch.Size([3072]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: tensor at position 35:
[rank0]: saved metadata: {'shape': torch.Size([16384, 3072]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: tensor at position 45:
[rank0]: saved metadata: {'shape': torch.Size([3072, 8192]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}
[rank0]: recomputed metadata: {'shape': torch.Size([0]), 'dtype': torch.bfloat16, 'device': device(type='cuda', index=0)}

```

Found a similar [issue](https://github.com/huggingface/transformers/issues/28499#issue-2080927400)
Tried the solution as mentioned, 

adding `  use_cache=False ` while loading the model in the train.py 
to enforce the model does not maintain past_key_values when you perform model training with activation checkpointing enabled.
Solution didn't work out..

In my case the recomputed metadata tensors are [0]

**Comment by 2U1** [comment]
Can you use the older version of my repo? I will check the issue a bit later that I'm bit busy right now. 
Thanks for the issue. I'll try to fix it asap.

**Comment by songrong137** [comment]
可能与您的GPU 精度不支持有关

**Comment by 2U1** [comment]
@ephron-canopy It is caused by gradient checkpointing. It was fine when I was using the older versions of pytorch and deepspeed. However It causes error when updating these to use memory-efficient training.
You could change the `{"use_reentrant": False}` to True. 
I'll fix it for now. 

Sorry for the issue.

**Comment by chentianyi16** [comment]
> @ephron-canopy It is caused by gradient checkpointing. It was fine when I was using the older versions of pytorch and deepspeed. However It causes error when updating these to use memory-efficient training. You could change the `{"use_reentrant": False}` to True. I'll fix it for now.
> 
> Sorry for the issue.
> 
> Also I recommend to update your deepspeed version to `deepspeed==0.15.4`

It looks like a PyTorch bug. This issue seems similar https://github.com/pytorch/pytorch/issues/141896

**Comment by 2U1** [comment]
@chentianyi16 Thanks for letting me know. I've changed the code for temperal fix. It works for now.

**Comment by ephron-canopy** [comment]
@2U1 
Sorry for the late comment...
Thanks for fixing the issue, it works fine for me...🎉
